services:
  - type: web
    name: multi-document-rag-backend
    runtime: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false # You will be prompted to enter this in the dashboard
      - key: ALLOWED_ORIGINS
        value: "*" # Allows frontend to connect
      - key: LLM_MODEL
        value: gemini-flash-latest
      - key: EMBEDDING_MODEL
        value: gemini-embedding-001
      - key: CHROMA_DB_DIR
        value: ./chroma_db
